<?php

namespace App\Models;

use App\Collections\BaseCollection;
use App\Scopes\BaseScope;
use Illuminate\Database\Eloquent\Model;

class MainBase extends Model
{
    //
    protected $connection           =   'mysql';
    protected $primaryKey           =   'uuid';
    protected $keyType              =   'string';
    protected $perPage              =   15;
    public $incrementing            =   false;
    public $timestamps              =   false;


    public function newCollection(array $models = [])
    {
        return new BaseCollection($models);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

//        static::addGlobalScope( new BaseScope() );
    }

    public function scopeStatus ($query)
    {
        return $query->where( 'status', 1 );
    }
}
